-- Migration 006: Add duplicate_cluster_id and verify all post columns
-- Target Database: PostgreSQL

ALTER TABLE posts 
ADD COLUMN IF NOT EXISTS duplicate_cluster_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS location_accuracy_meters DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS location_source VARCHAR(50),
ADD COLUMN IF NOT EXISTS location_captured_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS canonical_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS normalized_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS landmark_type VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS ai_confidence DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS place_id INTEGER;
